name: LH-git-actions
description: LogicHub git actions

inputs:
  CHECK:
    required: true
  GITHUB_TOKEN:
    required: true
  JIRA_HOST_URL:
    required: false
  JIRA_PROJECT_NAME:
    required: false
  PR_TITLE_REGEX:
    required: false

runs:
  using: 'node16'
  main: dist/index.js

branding:
  icon: git-pull-request
  color: red
